lector_list = [
    'lector_Вася',
    'lector_Петя',
    'lector_Коля',
    'lector_Саша',
    'lector_Ваня',
    'lector_Леша',
    'lector_Ваня',
    'lector_Юра',
    'lector_Володя',
    'lector_Паша',
    'lector_Даня',
    'lector_Сережа',
    'lector_Женя',
    'lector_Лена',
    'lector_Катя',
    'lector_Даша',
    'lector_Света',
    'lector_Маша',

]

lector_tegs = {
     'skill_быстрый',
    'skill_сильный',
    'skill_смелый',
    'skill_высокий',
    'skill_красивый',
    'skill_умный',
    'skill_ловкий',
    'skill_хитрый',
    'skill_дальновидный',
    'skill_образованый',
    'skill_храбрый',
    'skill_лютый',
    'skill_веселый',
    'skill_увереный',
    'skill_спокойный',
    'skill_холоднокровный',
    'skill_авторитарный',
    'skill_дисциплинированный',
}